### ISSUE TITLE
stream's languages are still missed

### ISSUE THREAD

**Issue by lonecrane** [Guymer/PyGuymer#1]
Hi Guymer,

I would like to demux blu-ray according to the language of the streams, which necessity detecting the language information of all the streams. Fortunately I find your nice code form here
http://www.thomasguymer.co.uk/blog/2018/2018-02-21/

In this code you get the language imformation from the mpls file. However, it is not feasible as actually it is stored inside the correlated clpi files, according to
https://github.com/lerks/BluRay/wiki/CLPI

Best regards

**Comment by Guymer** [comment]
The language information of *movies* is stored in MPLS files. The language information of *clips* is stored in CLPI files. My module loads MPLS files to extract the information about the *movies* to allow the *movies* to be demuxed - this works very well in my experience. If you want to demux the *clips* then you need to parse the CLPI files, which I have not done in my module.

**Comment by Guymer** [comment]
([pyguymer](https://github.com/Guymer/PyGuymer) is deprecated, by the way, you should be using [pyguymer3](https://github.com/Guymer/PyGuymer3) instead)

I have just written a function to apply the MPLS parsing to a CLPI file: [pyguymer3.parse_CLPI_file()](https://github.com/Guymer/PyGuymer3/blob/master/parse_CLPI_file.py). This works *a little bit*. Some of the information is extracted from the file, but I cannot see any language information in the dictionary that it returns. Now, this is probably because the CLPI files are in an entirely different format to the MPLS files. I will open a ticket on [pyguymer3](https://github.com/Guymer/PyGuymer3) to add CLPI support (I have no idea how much work that will be).

**Comment by Guymer** [comment]
I have now created the ticket https://github.com/Guymer/PyGuymer3/issues/2 to add support for CLPI files to [pyguymer3](https://github.com/Guymer/PyGuymer3).
